### ISSUE TITLE
GPIO IN/OUT macros reversed

### ISSUE THREAD

**Issue by opoei** [SamsungARTIK/TizenRT#2]
Title. You're setting GPIO_OUT when you want to read, and GPIO_IN when you want to write.

**Comment by JunhwanPark** [comment]
Hello @opoei ,
Please tell me detail.

**Comment by opoei** [comment]
See this implementation: https://github.com/SamsungARTIK/TizenRT/blob/artik/apps/examples/artik_examples/gpio-api.c

To define gpio direction we use a macro. For example in gpio_read(), GPIO_OUT is used. This is counter intuitive as for a READ function we look to take an INput

**Comment by glemercier** [comment]
@opoei, thanks for reporting. We will fix this discrepancy before next release.

**Comment by JunhwanPark** [comment]
Hello @opoei ,
Please check 0fae2c913c0d83dd2b4e0c8d111f948b6ce893f8.
Thank you for reporting.
