### ISSUE TITLE
gpio-api read has a memory leak.

### ISSUE THREAD

**Issue by opoei** [SamsungARTIK/TizenRT#3]
On the artik 053, SDK 1.7.0. If an pin is polled using the read function, you will eventually fail to successfully request the same pin. Does` artik_gpio_config config` need to be released?

Additionally it may be helpful if the api allows for gpio's to be initialized / released by the end developer. This way they can request the GPIO pin, do whatever for however long, and then release it.

**Comment by JunhwanPark** [comment]
Hello @opoei ,
We fixed this issue in https://github.com/SamsungARTIK/artik-sdk/commit/08bfe76c1abcd3e2a66683e3812af55e91bbe942.
As you know, TizenRT and ARTIK-SDK are connected to each other. If you update TizenRT to the latest version, you can check the above ARTIK-SDK.
